spring:
  application:
    name: lms
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lms}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: none
      default_batch_fetch_size: 1000
      jdbc:
        time_zone: Asia/Seoul
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}

server:
  host: ${DEV_URL:http://54.180.78.104:8080}
  port: 8080

jwt:
  access-secret-key: ${ACCESS_SECRET_KEY}
  refresh-secret-key: ${REFRESH_SECRET_KEY}
  access-token-validity-in-seconds: ${ACCESS_VALIDITY_SECONDS}
  refresh-token-validity-in-seconds: ${REFRESH_VALIDITY_SECONDS}